import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Obsidian Kinetic Design System Colors (from stitch)
        "primary-fixed": "#ffddaf",
        "surface-tint": "#ffba43",
        "surface-container-highest": "#353534",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "outline-variant": "#524533",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#1a1c1c",
        "outline": "#9f8e78",
        "on-secondary-fixed": "#002022",
        "background": "#131313",
        "on-surface-variant": "#d7c4ac",
        "surface-container-lowest": "#0e0e0e",
        "surface": "#131313",
        "inverse-primary": "#805600",
        "surface-bright": "#3a3939",
        "secondary-fixed": "#7df4ff",
        "surface-container-low": "#1c1b1b",
        "surface-variant": "#353534",
        "primary-fixed-dim": "#ffba43",
        "tertiary-fixed-dim": "#c6c6c7",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#313030",
        "on-primary": "#432c00",
        "primary": "#ffd597",
        "on-secondary-fixed-variant": "#004f54",
        "on-tertiary": "#2f3131",
        "tertiary-container": "#bebfbf",
        "tertiary-fixed": "#e2e2e2",
        "error": "#ffb4ab",
        "primary-container": "#ffb000",
        "tertiary": "#dbdbdb",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#00dbe9",
        "on-secondary": "#00363a",
        "on-tertiary-container": "#4c4e4e",
        "on-secondary-container": "#00686f",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "secondary-container": "#00eefc",
        "on-primary-container": "#6a4700",
        "on-primary-fixed": "#281800",
        "on-primary-fixed-variant": "#614000",
        "secondary": "#d3fbff",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
